### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by champmq** [Wertzui123/Rewards#2] opened 2019-03-23 20:37 UTC
[18:23:24] [Server thread/CRITICAL]: ReflectionException: "Class Wertzui123\Rewards\PlayerJoinEvent does not exist" (EXCEPTION) in "src/pocketmine/plugin/PluginManager" at line 740

**Comment by Wertzui123** [comment] 2019-03-24 09:13
I hope the problem is solved now. @ChampOfGamesYT

**Comment by champmq** [comment] 2019-03-24 12:51
Same problem again.

**Comment by Wertzui123** [comment] 2019-03-24 15:48
Ok, I'll look at in in a few hours or tomorrow

**Comment by Wertzui123** [comment] 2019-03-25 13:15
I hope its fixed now! @ChampOfGamesYT

**Closed as completed** 2019-03-25 21:10 UTC
